import React from "react";
import { StyleSheet, Platform, StatusBar } from "react-native";
const d = StyleSheet.create({
  fd: {
    backgroundColor: '#420C4D',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  reps:{
    textAlign: 'center',
    borderWidth: 1,
    borderColor: 'white',
    width: 200,
    borderRadius: 50,
    backgroundColor: '#0B0226',
    padding:10,
    top:140,
    marginTop:10,
  },
  title: {
    position: 'absolute',
    top: 150,
    color: 'white',
    fontSize: 32,
    textAlign: 'center',
    backgroundColor: '#210327',
    // padding:10,
    borderBottomWidth: 4,
    width: '100%',
    borderTopWidth: 4,
    paddingBottom: 25,
    paddingTop: 25,
  },
  dollar: {
    left: 40,
    top: 60,
    borderWidth: 2,
    backgroundColor: '#D8B90C',
    position: 'absolute',
    borderColor: '#D8B90C',
    borderRadius: 50,
    paddingLeft: 10,
    paddingRight: 10,
    color: 'white',
    fontSize: 24,
  },
  score: {
    left: 250,
    top: 60,
    position: 'absolute',
    borderWidth: 2,
    borderRadius: 50,
    paddingLeft: 20,
    paddingRight: 20,
    borderColor: '#D8B90C',
    backgroundColor: '#D8B90C',
    color: 'white',
    fontSize: 24,
  },
  ans: {
    color:'white',
    textAlign: 'center',
    fontSize:24,

  },
vs:{
  color :'white',
  position: 'absolute',
  top:90,
  fontSize:24,
},
mp:{
  color :'white',
  borderWidth:2,
  alignItems:'center',
  fontSize:24,
  width:220,
  marginTop:20,
  textAlign: 'center',
  borderRadius:50,
  backgroundColor:'#D8B90C',},
np:{
  color :'white',
  alignItems:'center',
  borderWidth:2,
  width:220,
  fontSize:24,
  textAlign: 'center',
  marginTop:20,
  borderRadius:50,
  backgroundColor:'#D8B90C',
},
q:{
  color :'white',
  alignItems:'center',
  borderWidth:2,
  fontSize:24,
  width:220,
  marginTop:20,
  textAlign: 'center',
  borderRadius:50,
  backgroundColor:'#D8B90C',
},
retour:{
  position: 'absolute',
  top:650,
  left:300,
  color:'white',
},
retr:{

  color:'white',
},



});
export { d };